### ISSUE TITLE
Header block doesn't change even when you're in a different section of the site

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#11] opened 2015-08-20 15:20 UTC

**Comment by jronmorgan** [comment] 2015-09-25 11:44
Where should I look to see intended behavior? Isn't it normal for a header block to remain the same for a given site?

**Comment by mashanadavis** [comment] 2015-09-25 13:44
Here's a screenshot: ![error-nav-secondary-page-header fw](https://cloud.githubusercontent.com/assets/13887931/10101953/e328ee10-6369-11e5-96a7-ff272d3a655b.png)

**Comment by tgifford-webfirst** [comment] 2015-10-26 17:44
Let's call the block in question the "section header". Based on Mashana's description, the section header should correspond to the top-level menu item that the current page is found under. A similar functionality is frequently implemented by changing the color of the top-level menu item, but that presents accessibility issues, hence this implementation (conjecture).

If that is the case, the current implementation is sub-optimal. For all web page content type nodes that don't have the path "/contact", "Training & Events" is hard-coded in block and shown via a Context. However, if the Training & Events section of the site was the only section intended to have a section header, the approach would make more sense (although that seems unlikely).

Should every section have a section header? If so, the section header should be provided by a custom module block that retrieves the current section based on the active menu tree (and possibly other considerations for content not directly linked in the menu).

**Comment by mashanadavis** [comment] 2015-10-26 19:09
Every section or global navigation menu should have a section header, except HOME.



On Oct 26, 2015, at 1:44 PM, tgifford-webfirst <notifications@github.com<mailto:notifications@github.com>> wrote:


Let's call the block in question the "section header". Based on Mashana's description, the section header should correspond to the top-level menu item that the current page is found under. A similar functionality is frequently implemented by changing the color of the top-level menu item, but that presents accessibility issues, hence this implementation (conjecture).

If that is the case, the current implementation is sub-optimal. For all web page content type nodes that don't have the path "/contact", "Training & Events" is hard-coded in block and shown via a Context. However, if the Training & Events section of the site was the only section intended to have a section header, the approach would make more sense (although that seems unlikely).

Should every section have a section header? If so, the section header should be provided by a custom module block that retrieves the current section based on the active menu tree (and possibly other considerations for content not directly linked in the menu).

**Comment by tgifford-webfirst** [comment] 2015-10-26 19:15
For now, the other exception will be content that is not linked from the main menu. If we discover content that is not (and should not be) linked from the main menu, but should still have a section header, we will address that in a follow-up ticket.

**Comment by tgifford-webfirst** [comment] 2015-10-30 21:24
The new menu framework is ready to be moved to staging. This will require some upheaval as links are moved into the main menu and new styles are applied. I will coordinate this with you on Monday to minimize disruptions.

**Comment by jronmorgan** [comment] 2015-10-31 00:16
Everything is currently in dev where it can be looked at?  I am playing with one of the menu options and just want to make sure I have everything current.

-john

________________________________

**Comment by tgifford-webfirst** [comment] 2015-10-31 00:39
No, it is not in dev yet. It involves moving a lot of menu items, so I was
hoping to only do that once. If it needs to be seen in dev first, I would
want to stop all modifications on stg, pull the db to dev, update the
menus, then if approved push the db and code to stg. If Monday is not a
good day to do that, please weigh in here.

An alternative is to push my local partial implementation on dev, then make
the full set of changes on stg.

**Comment by jronmorgan** [comment] 2015-10-31 01:31
No, its fine.. I haven't really figured out a good way yet to fix the login menu issue I was having and so maybe once your changes are up it will be easier. That was kind of the last thing I was playing with for the whole login sequence. I can wait.

Question: did any of the changes involve the functions nihl_forms/nihl_forms.module:my_custom_log_in_form() and my_custom_log_in_form_submit()?  Not a big deal if it did as its pretty simple and I can rework it to whatever is current pretty quickly.

BTW, getting rid of the magic numbers on the setup and switch statements worked fine. ( I hate magic numbers, dammit, what was 42 again?).

-john

________________________________

**Comment by tgifford-webfirst** [comment] 2015-11-02 20:30
There weren't any changes to nihl_forms.

**Comment by tgifford-webfirst** [comment] 2015-11-03 14:59
Now that we have all the links in the main menu, the breadcrumbs are working. That means there will be a lot of redundant navigation elements. If you are on a Services page, there will be three locations that say "Services":

* The main navigation menu (currently it gives no indication when you are in the Services section)
* The section header (no link)
* The breadcrumb (linked)

This is redundant. Can we just remove the section header?

**Comment by cmndr-king** [comment] 2015-11-03 18:43
Yes, you can remove the section header.

Do you have a suggestion on how best to indicate which part of the menu you are in?



-James
_______________________________
James King, MLS, FSLA

http://about.me/cmndr_king


-------- Original message --------

**Comment by tgifford-webfirst** [comment] 2015-11-03 21:14
There is a graphical hover state that indicates which menu section is "hovered". We could do something similar for the active section.

In terms of accessibility, the [aria-current attribute](http://www.w3.org/TR/wai-aria-1.1/#aria-current) is not supported on most screen readers yet, but the breadcrumb can give the same context. There are [other approaches](http://www.heydonworks.com/article/the-accessible-current-page-link-conundrum) as well. Do you want to track the accessibility implementation in another issue? There may be other concerns to address on that front as well.

**Comment by tgifford-webfirst** [comment] 2015-12-02 15:03
Graphical style applied.

**Comment by cmndr-king** [comment] 2015-12-02 19:35
Marking this as closed.

**Closed** 2015-12-02 19:35 UTC
Labels: bug, general website, navigation, PRIORITY

**Comment by cmndr-king** [comment] 2015-12-02 19:45
There is an accessibility issue that will need to be resolved in the future with this solution.  The indicator is graphical which will not translate to a screen reader.
