### ISSUE TITLE
<nolink> is included in the path alias for some nodes when [node:menu-link:parent:url:path]/[node:title] is used as the pattern

### ISSUE THREAD

**Issue by tgifford-webfirst** [NIHL/Drupal7-Migration#134] opened 2016-04-27 14:03 UTC

**Comment by mashanadavis** [comment] 2016-05-27 16:15
Was this a duplicate of #142?

<nolink> does not appear in the breadcrumbs or path alias. However, the nolink category still appears. Is there a way to remove this? Desired outcome: Home > Services > Data Services. If not then we'll have to think about another solution, like removing the subheaders.

Additionally, the breadcrumbs for 6 out of 11 service areas is incorrect. The breadcrumb should be Home > Services > Library Services > NAME, but it appears as Home > NAME. I will check the path alias and navigation for these pages/guides.

**Comment by alwaysmashana** [comment] 2016-06-15 20:19
Please see ticket #119 for reference. The menu subheadings should not appear in the breadcrumb (e.g. general information, policies and procedures, requests, library services, facilities, online databases, online journals, other resources).

Now the breadcrumb reads Home > Level 1 > nolink heading.

**Comment by gbohara** [comment] 2016-06-21 19:13
If landing pages are to be created for Sub-headings, it makes sense to put menu-subheadings in breadcrumbs as well as URL alias.

There was discussion about creating landing pages for Sub-headings and use those in the breadcrumbs. Is that still valid?

**Comment by alwaysmashana** [comment] 2016-06-22 15:48
Based on our discussion at the June 22 meeting, we will not create webpages for the subheadings (e.g. General Information), rather pages would be created for the global navigation options (e.g. Services). Please remove any <nolink> or subheading from the breadcrumbs and URL patterns.

**Comment by gbohara** [comment] 2016-06-24 12:55
What is Staff Publication?  
There is not a single content for Staff Publication. Do we need this or can this be deleted?

**Comment by alwaysmashana** [comment] 2016-06-24 17:24
Staff Publication will be used for our staff publications---presentations, posters, and papers produced by our staff. We have a list on our current website: http://nihlibrary.nih.gov/AboutUs/Pages/StaffPresentationsAndPublications.aspx.

**Comment by stanleymurgolo** [comment] 2016-06-24 18:36
Hi MaShana,

Cindy and I have talked about updating this, I believe it's on our list of to-do's but has been put off due to other priorities for now. I will bring it up again to Kathleen and Cindy and maybe we can get it updated in the next month or two.

**Comment by gbohara** [comment] 2016-06-29 15:30
- Menu Position Rule added for FAQ's.
- Url Alias Pattern changed for FAQ's and updated in bulk.
- Url aliases for WebPages updated in bulk.

**Comment by gbohara** [comment] 2016-06-29 16:16
Please test.

1. Links Under About Us (Everything looks correct)
2. Links under Training and Events
   - Fix Breadcrumb for Training & Events > Classes
   - Training and Event > Request a Turotial (**Links from multiple menu items**). 
      Links from: Services > Requests > Request a Tutorial

3. Links Under Services > Library Services
  - Services > Library Services > Bioinformatics Support Program > Bioinformatics Consult (**incorrect parent menu item?**)
 - Services > Library Services > Bioinformatics Support Program > Bioinformatics Resources Registration (**incorrect parent menu item?**)
   - Services > Library Services > Data Services Program > Gephi (**Does not have Left navigation**)
   - Services > Library Services > Editing Service > Submit and Editing Request (**incorrect parent menu item?**)
4. Links Under Services > Requests
  - Services > Requests > Bioinformatics Consult (**Links from multiple menu items**)
  - Services > Requests > Bioinformatics Resource Registration (**Links from multiple menu items**)
  - Services > Requests > Editing Request (**Links from multiple menu items**)
  - Services > Requests > Request a tutorial (**Links from multiple menu items**)

5. Links Under Resources
   - Resources > Other Resource Tools > Subject Guides (**incorrect parent menu item?**)

- **Should we correct the incorrect parent menu item or was it intentionally left that way?**
- **What should we do with the pages that are linked from multiple menu items?**
- **How important is the Breadcrumbs / URL when clicking these links** (multiple menu items)?

(Seems like all of these are for webforms. We could optionally create pages and insert webforms as blocks if the URL and Breadcrumbs are really important for these pages.)

**Comment by alwaysmashana** [comment] 2016-06-29 18:40
About Us section – resolved.

Training & Events > Classes – duplicate in breadcrumb; URL is fine.

Incorrect parent menu items and links from multiple places.
This is usually related to forms. We want to connect the form to the relevant service area, while allowing users a view of all available forms. How do we achieve this without messing up the navigation or confusing the user?

Services > Library Services > Data Services – this whole section needs to be revisited.

Subject Guides lives under Resources, not Training & Events. This is a View. I updated the path on the View, and added a menu item under main-menu > Resources > Other Resources. The breadcrumbs should be adjusted (Home > Resources). Is this correct?

Thanks.

**Comment by gbohara** [comment] 2016-06-29 19:30
The breadcrumb was not adjusted. 
The views menu setting automatically creates menu. It just needed to move to the correct hierarchy. 
I guess you did manually create the menu and put views path in the path field. The breadcrumb was not showing properly that way.

**Comment by alwaysmashana** [comment] 2016-07-06 12:43
When you create a View you usually create the URL. So, how do you fix the breadcrumbs for Views?

**Comment by alwaysmashana** [comment] 2016-07-26 13:54
See ticket #204. A new ticket was created to address this.

**Comment by alwaysmashana** [comment] 2016-07-26 18:43
Testing on PROD:

About Us > Announcements & News: clicked on news story "Join Us at the Bioinformatics Symposium" and clicked the assigned NIH Subject "Bioinformatics. It took me to the search results page, but the breadcrumb read Home > Resources > Bioinformatics.

In other searches, the breadcrumb is Home > Search > Search results > [search string].

**Comment by gbohara** [comment] 2016-07-29 13:17
This is a different issue (MaShanas last comment) and it is not only related with News Story. 
The same breadcrumb with resources appears if you do a blank search. 
http://nihlibrary.prod.acquia-sites.com/search/site

Also after performing blank search if you click on facets, the breadcrumb is different eg. (Home > Resources > Tool)

**Comment by alwaysmashana** [comment] 2016-08-01 14:59
Blank search returns Home > Resources as breadcrumb and an error message to the user "Please enter some keywords." This using the search box in the gold bar. When on the search results page, submitting a blank search results in the same breadcrumb but no error message.

**Comment by alwaysmashana** [comment] 2016-08-02 18:02
Should a new ticket be created to address the breadcrumb issue? I believe the original issue was resolved.

**Comment by gbohara** [comment] 2016-08-02 18:11
Yes Please.

**Closed** 2016-08-02 19:43 UTC
Labels: ready
