### ISSUE TITLE
Instruction: Handling off-site registration and registration for classes that are offered as webinar and in-person

### ISSUE THREAD

**Issue by alwaysmashana** [NIHL/Drupal7-Migration#53] opened 2015-10-09 18:07 UTC
Registration for some classes will be handled by another registration system, mainly the LMS or for webinars, GoToWebinar, WebEx, etc. Currently, the website only supports registration for in-person classes. We need to support both options. 

In addition, there will be some classes that are offered in-person and simultaneously as a webinar. Attendees can register for either format. We need to support this. 

The current solution is to add the URL to the webinar to the class description.

Does the current registration module support this? 

The current workaround is to add the URL to the webinar in the class description.

**Comment by tgifford-webfirst** [comment] 2016-05-04 15:22
Is #137 a dupe of this?

**Comment by mashanadavis** [comment] 2016-05-05 19:15
Yes I believe 137 is the duplicate. Do we need to separate the two issues in this ticket or are they the same issue? If the former than we can use 137 for the other issue.

Just a thought.

**Comment by gbohara** [comment] 2016-05-23 20:35
If it is  only "Webinar",  does it mean that it should not have the registration form on the page and just the Webinar registration link?

**Comment by stanleymurgolo** [comment] 2016-05-23 20:42
Yes

**Comment by gbohara** [comment] 2016-05-26 19:44
This feature has been added and is not on the production site.

Here are the scenarios that can be tested.
1) Only webinars 
     For webinars only,  the registration can be disabled. (it is a good practice to disable, since we won't be using the registration form.  However, even if registration is enabled and only "Webinar" is selected as Training format option, it will only display the webinar registration link. 
 A new field "webinar registration URL" has been added which is visible only when "webinar" is checked.
The webinar registration link gets hidden once the date for the registration is passed.

2) Normal Registration(ie. without webinar): works as is
3) Both webinars and normal registration
    a) Both the registration form as well as the webinar registration link is displayed.
    b) Once the space for registration is full,  it hides the registration form and displays only the webinar link with 
"Registration Only open for Webinar
There is no limit for webinar registrations." message at the top.
  c) If there is waitlist, it shows the form as well as webinar registration link
  d) If the waitlist is full, it only shows the webinar registration form (if the close date is not passed)

NOTE: The page is not themed yet.

**Comment by gbohara** [comment] 2016-05-26 19:58
This functionality can be tested on dev site http://nihlibrarydev.prod.acquia-sites.com/

**Comment by alwaysmashana** [comment] 2016-07-06 12:52
Stanley - Can you verify that this is working?

**Comment by stanleymurgolo** [comment] 2016-07-06 15:31
Couldn't test on the Development site, but tested on the Production site and it worked fine. Ganga, my only suggestion is for 3b, can we reword to say "Registration to attend this class in-person is now full, however registration to attend this class by webinar is available and open."

**Comment by gbohara** [comment] 2016-07-08 14:02
Closing this ticket.  #190 will take care of this.

**Closed** 2016-07-08 14:02 UTC
Labels: enhancement, instruction
