### ISSUE TITLE
Customer Group: selecting HHS doesn't cascade down to subagencies

### ISSUE THREAD

**Issue by alwaysmashana** [NIHL/Drupal7-Migration#110] opened 2016-04-01 17:17 UTC
News stories were added and assigned to NIH, Public, and HHS, but they did not appear on the ACF agency homepage until ACF was actually selected. 

So HHS is not inclusive. This may be a good thing to restrict content to specific subagencies. We are fine with explaining this to our users, unless this is an easy fix.

**Comment by svpatel1** [comment] 2016-04-18 19:49
MaShana, we can make either one work, just let us know which way you prefer.

**Comment by mashanadavis** [comment] 2016-04-18 19:51
Hi Sanjay. To my understanding both should work. If I select “HHS” then it should apply to all subagencies. If I select an individual subagency (e.g. OCR) then it should only apply to that subagency. Right now the latter option works.

**Comment by tgifford-webfirst** [comment] 2016-04-18 20:02
I think Sanjay was asking if you wanted to show news stories from parents on the child agency pages. It sounds like the answer is yes, and we will make it so.

**Comment by mashanadavis** [comment] 2016-04-19 17:22
We are using a workaround for this. So, if you need to move this to Beta 2 for another priority, that's completely fine.

**Comment by tgifford-webfirst** [comment] 2016-05-11 13:51
Need to verify if other pages/locations require similar treatment.

**Comment by tgifford-webfirst** [comment] 2016-05-11 21:03
The only similar situation I could find was the view block right next to the "Read the Latest News" block on the homepage: "Upcoming Training". I've updated it using the same technique, tested, and published to prod.

**Comment by mashanadavis** [comment] 2016-05-13 15:49
The issue is with the widget being used for this taxonomy under the content type. Any content type using this taxonomy, which is everything, is encountering this issue.

**Comment by tgifford-webfirst** [comment] 2016-05-13 15:52
Ah, I thought you wanted to only select e.g. HHS, and have the content show for all HHS children. Are you saying you want to have to select all the children explicitly (but automatically) for content to show? The problem with that approach is new children aren't selected automatically if they are added to the taxonomy after the content in question is edited.

**Comment by mashanadavis** [comment] 2016-05-13 16:51
Selecting HHS should cascade down to all groups list under this group. Same with OS or IHS.

**Comment by tgifford-webfirst** [comment] 2016-05-13 17:27
I understand you want a cascade from parent to child, but that didn't quite answer my question. Which of the following describes the requirement?

### Widget Options: Pick as many as desired

- [ ] Option 1: When I select an un-selected parent customer group on a content edit form, I want the customer group widget to automatically select all children of that customer group.
- [ ] Option 2: When I un-select a selected parent customer group on a content edit form, I want the customer group widget to automatically un-select all children of that customer group.

### Access Options: Pick one
- [ ] Option 3: When I select a parent customer group on a content edit form, I want the content to be accessible by all child customer groups (selecting HHS, but not ACF, results in ACF having access to the content).
- [ ] Option 4: When I select a parent customer group on a content edit form, I want the content to be *in*accessible by all un-selected child customer groups (selecting HHS, but not ACF, results in ACF being denied access to the content).

### Listing Options: Pick one
- [ ] Option 5: When I select a parent customer group on a content edit form, I want the content to be displayed on lists in the context of all child customer groups (for a news story: selecting HHS, but not ACF, results in the story being listed on the ACF homepage).
- [ ] Option 6: When I select a parent customer group on a content edit form, I *do not* want the content to be displayed on lists in the context of all un-selected child customer groups (for a news story: selecting HHS, but not ACF, results in the story *not* being listed on the ACF homepage).

**Comment by cmndr-king** [comment] 2016-05-13 19:48
Ted - I believe we want there to be a HHS checkbox that, when selected, automatically selects all of the children and grandchildren under it.  That means that if we add a news item or new resource and choose HHS, all entities underneath should be selected and have access.  We want to be able to open up the HHS tree and unselect an agency or group so that they do not get the news story.  In addition, we want to be able to not select HHS but select one child or grandchild.  Furthermore, if we select OS or IHS, it should automatically select the grandchildren under those options.  If we add a new site to the taxonomy at a later date, we'll have to do some database work to have that automatically added to resources that have HHS selected.  Options 1, 2, and 6 seem to align with what we're thinking.

**Comment by tgifford-webfirst** [comment] 2016-05-13 20:21
That is helpful. It sounds like you don't anticipate adding child agencies frequently, which makes sense.

It sounds like the most common use case is that you want to hide an item (e.g. news) from one specific child or grandchild, as opposed to showing the item to one specific child or grandchild. Is that correct (or at least a toss-up)?

Is there an easy answer to option 3 or 4? Should it be the same as the option 5/6 answer? If so, we may be able to simplify the spreadsheet on basecamp.

I also assume that you want all the selections to be by checkbox, not just the HHS/first-level items.

**Comment by mashanadavis** [comment] 2016-06-07 20:22
Met with Sanjay and Ted on June 6 to discuss this ticket. Outcomes: 

- Revisit widget options at a later date
- Access options = Option 3
- Listing options = Option 6

**Comment by gbohara** [comment] 2016-06-28 16:06
**Example formatting options. More items can be added to the list. Once verified, we can check the option to mark as verified.**
- [x] Example Formating Checkbox
- [ ] Example Formating Checkbox

MaShana, Brian, Stanley, Please test this.
- **Lists (option 6)**
 - [ ] Home Page Upcoming Training
 - [ ] Home Page Latest News
 - [ ] [Training and Events Page] (http://nihlibrary.prod.acquia-sites.com/training/calendar)
 - [ ] [Announcements and News] (http://nihlibrary.prod.acquia-sites.com/about-us/news)
 - [ ] [Search Results] (http://nihlibrary.prod.acquia-sites.com/search/site/test)

 - **Individual Item (option 3)**
 For individual item, edit [this] (http://nihlibrary.prod.acquia-sites.com/about-us/news/test-news-item-will-be-deleted) page and Select HHS as Customer Group. This should not be listed in [Announcements and News] (http://nihlibrary.prod.acquia-sites.com/about-us/news) or in Home Page Latest News. However, this should be visible if you copy and paste the whole url (http://nihlibrary.prod.acquia-sites.com/about-us/news)

**Comment by alwaysmashana** [comment] 2016-07-06 12:44
My apologies for the late response. This fell off of my plate. We were supposed to discuss this last week. What do you want us to test here?

**Comment by alwaysmashana** [comment] 2016-07-06 18:00
The options were misrepresented. The options should be Options 3 and 5 for folks who are logged in. The "Public" anonymous users should have the same listing as NIH, but access is limited (specifically class registration and electronic resources).

WebFirst will review hierarchical widgets and select the best one.

**Comment by gbohara** [comment] 2016-07-19 14:57
![img_20160606_140104](https://cloud.githubusercontent.com/assets/14879144/16954499/1326d7ec-4d9f-11e6-8ea0-e988c7f09e5b.jpg)

Public can access all the content other than "resources" and "training" that have NIH as customer group( including the ones that do not have 'Public' as customer group).

This was the reason why public had access to news item in yesterday's demo (18th July 2016).

Do we really need to restrict access to public for items other than resources and training?

**Comment by svpatel1** [comment] 2016-07-19 15:08
Just to clarify a bit - we did implement this access restriction (i.e public can list but not view), - we were demoing the NEWS items yesterday. Do we want to restrict news in this way? Or keep it just for resources and training as described in the picture above?

**Comment by alwaysmashana** [comment] 2016-07-26 18:54
Restrictions should be on Resources and Training, not so much for News. Does that make sense? If so, then can we close the ticket?

**Comment by gbohara** [comment] 2016-07-27 13:22
I think we can close this ticket. Currently it has restrictions on Training and Resources. All other content that belongs to NIH can be accessed by public.

**Closed** 2016-07-27 13:41 UTC
Labels: bug, PRIORITY, ready
