### ISSUE TITLE
Instruction: Date and time not captured on Training Session

### ISSUE THREAD

**Issue by mashanadavis** [NIHL/Drupal7-Migration#113] opened 2016-04-07 17:50 UTC
[Sent an email to Ted]

Upon creating and saving a new session, the time is not captured correctly. And, editing the draft doesn't fix the issue. 

We have a number of classes to enter and this is holding up progress.

**Comment by tgifford-webfirst** [comment] 2016-04-12 18:11
I am not able to reproduce this. Did someone switch the date data entry widget or otherwise try to address this? If not, please provide further detail on how to reproduce the bug.

**Comment by tgifford-webfirst** [comment] 2016-04-12 18:11
I tested in Firefox.

**Comment by MarcellaFredriksson** [comment] 2016-04-12 19:41
I just created a new training session and could not recreate the time capture issue. I tried editing an already published session and editing a draft.  The time and date remained accurate in both instances (in IE).

However, the new session I created did not show up on the calendar or list view on the Training page. 

New session - January 12, 2-3 pm
http://nihlibrarystg.prod.acquia-sites.com/content/uprint-3d-printer-training

Not listed here 
http://nihlibrarystg.prod.acquia-sites.com/training/list/2016-01

**Comment by mashanadavis** [comment] 2016-04-19 15:54
Reopening this ticket. The issue is with past classes, not current training. Marcella attempted to edit a class from January (BTRIS) and the time did not stick. Date was fine. I created and saved a new class (MaShana's Test) and published it. And was able to edit and publish the class without errors. 

This is a bug with the module apparently. 

We can move this to Beta 2 Release.

**Comment by gbohara** [comment] 2016-04-25 18:38
Is this always going to be eastern time? Or 
Should it be displayed differently based on time zone?

**Comment by gbohara** [comment] 2016-04-25 18:50
When setting "site's timezone" for the field, it seems to have affected by this bug
https://www.drupal.org/node/998076

**Comment by gbohara** [comment] 2016-04-25 19:03
Converted "sites time zone" to none. It now displays exactly what is entered without converting the time. It means that you will see exactly the same time regardless of where you view it from or regardless of logged in user's timezone.

Marking this as fixed. 

Also looked for other date fields on the site, there are no settings for selecting timezone. So they should be just fine.
In case, If anybody wants to test those fields are:
1) Date Posted :  News
2) Date Posted :  Online Tutorial

**Comment by mashanadavis** [comment] 2016-04-25 20:13
Always EST. The library is located in that time zone.

**Comment by gbohara** [comment] 2016-04-26 15:29
Timezone set handling set to to "No time zone conversion". 
Also updated the previously entered dates (since it was saved in UTC) both in staging and production. 
Verified (in production) that all the updated dates match with the ones before update.

**Comment by MarcellaFredriksson** [comment] 2016-04-26 16:07
I was able to successfully edit and publish time changes to past training sessions

**Comment by mashanadavis** [comment] 2016-04-26 16:46
Since this has been confirmed, I'm closing the ticket.

**Closed** 2016-04-26 16:46 UTC
Labels: bug, content, instruction, PRIORITY, ready
